### ISSUE TITLE
Revamp Github Integration into Slack

### ISSUE THREAD

**Issue by ausshir** [UofSSpaceDesignTeam/usst-docs#2]
Split Git related actions (pull-requests etc) and Issues/Comments into their own channels

**Comment by nicole-parker** [comment]
@ottopasuuna Did you write some docs on how to add this integration into new repositories?

**Comment by ottopasuuna** [comment]
No, but I'll start working on it.

**Comment by ottopasuuna** [comment]
I made a wiki page on the integration, and also added the integration to the usst-docs repo. Doesn't quite work though.

**Comment by ottopasuuna** [comment]
Never mind, it does.
